FROM elasticsearch:2.4

# installing couple of UI plugins
# accessible at  /_plugin/head/   and  /_plugin/hq/

RUN /usr/share/elasticsearch/bin/plugin install royrusso/elasticsearch-HQ
RUN /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head