logging:
        level:
           root: "INFO"
           org:
            thymeleaf: "DEBUG"

project:
  base-dir: "file://${maven.multiModuleProjectDirectory}"



spring:
  thymeleaf:
    cache: false
    prefix: "${project.base-dir}/src/main/resources/templates/"
  resources:
    static-locations: "${project.base-dir}/src/main/resources/static/"
    cache-period: 0