kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-pv
  labels:
    name: elastic-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{{aws-elastic-pv-travel}}}
    fsType: ext4