kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvelastic.claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: "elastic-pv"